name: K6 Integration Tests
on:
  pull_request:
    branches: [ "**" ]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Run REST smoke (summary export)
        run: |
          mkdir -p k6/artifacts
          k6 run --summary-export k6/artifacts/restcountries-summary.json k6/rest/restcountries-smoke.js
      - name: Run GraphQL smoke (summary export)
        run: |
          k6 run --summary-export k6/artifacts/rickmorty-summary.json k6/graphql/rickmorty-characters.js
      - name: Upload k6 summaries
        uses: actions/upload-artifact@v4
        with:
          name: k6-summaries
          path: k6/artifacts
